export const products = [
    {
      slug: "titos-candle",
      name: "Titos Candle",
      price: 24.99,
      image: "/images/titos.png",
      sku: "DCW-0001",
      stripePriceId: "price_1SHV4MKrvd2Dq5RV3EdaRFpR",
      seoDescription: "Hand-poured candle in an upcycled Titos bottle.",
      bestSeller: true,
    },
    {
      slug: "casamigos-candle",
      name: "Casamigos Candle",
      price: 24.99,
      image: "/images/casamigos.png",
      sku: "DCW-0002",
      stripePriceId: "price_1SHV3xKrvd2Dq5RVuVNYWqWO",
      seoDescription: "Hand-poured candle in an upcycled Casamigos bottle.",
      bestSeller: true,
    },
    {
      slug: "stgermain-candle",
      name: "St. Germain Candle",
      price: 24.99,
      image: "/images/stgermain.png",
      sku: "DCW-0003",
      stripePriceId: "price_1SHV4uKrvd2Dq5RVNBQjAmn7",
      seoDescription: "Hand-poured candle in an upcycled St. Germain bottle.",
      bestSeller: true,
    },
    {
        slug: "la-crema-candle",
        name: "La Crema Pinot Noir Candle",
        price: 19.99,
        image: "/images/lacrema.png",
        sku: "DCW-0004",
        stripePriceId: "price_1SHV5HKrvd2Dq5RVkxi7i16s",
        seoDescription: "Hand-poured candle in an upcycled Wine bottle.",
      },
      {
        slug: "new-amsterdam-gin-candle",
        name: "New Amsterdam Gin Candle",
        price: 24.99,
        image: "/images/newamsterdam.png",
        sku: "DCW-0005",
        stripePriceId: "price_1SHYksKrvd2Dq5RVDFHcOV5H",
        seoDescription: "Hand-poured candle in an upcycled New Amsterdam Gin bottle.",
      },
      {
        slug: "pink-whitney-candle",
        name: "Pink Whitney Candle",
        price: 24.99,
        image: "/images/placeholder.png",
        sku: "DCW-0006",
        stripePriceId: "price_1SHYllKrvd2Dq5RVvtmFCBxD",
        seoDescription: "Hand-poured candle in an upcycled Pink Whitney bottle.",
      },
      {
        slug: "ruffino-prosecco-candle",
        name: "Ruffino Prosecco Candle",
        price: 19.99,
        image: "/images/ruffino.png",
        sku: "DCW-0007",
        stripePriceId: "price_1SHYm2Krvd2Dq5RVc16I4NgK",
        seoDescription: "Hand-poured candle in an upcycled Ruffino Prosecco bottle.",
      },
      {
        slug: "santan-espresso-martini-candle",
        name: "Santan Espresso Martini Candle",
        price: 24.99,
        image: "/images/santanespresso.png",
        sku: "DCW-0008",
        stripePriceId: "price_1SHYmPKrvd2Dq5RVO8gzjTkL",
        seoDescription: "Hand-poured candle in an upcycled Santan Spirits Espresso Martini bottle.",
      },
      {
        slug: "bacardi-candle",
        name: "Bacardi Candle",
        price: 24.99,
        image: "/images/bacardi.png",
        sku: "DCW-0009",
        stripePriceId: "price_1SHYmeKrvd2Dq5RVDWj6eWDg",
        seoDescription: "Hand-poured candle in an upcycled Bacardi bottle.",
      },
      {
        slug: "mi-campo-tequila-candle",
        name: "Mi Campo Tequila Candle",
        price: 24.99,
        image: "/images/micampo.png",
        sku: "DCW-0010",
        stripePriceId: "price_1SHYmvKrvd2Dq5RVLCpSrDbj",
        seoDescription: "Hand-poured candle in an upcycled Mi Campo Tequila bottle.",
      },
      {
        slug: "hendricks-gin-candle",
        name: "Hendrick's Gin Candle",
        price: 24.99,
        image: "/images/hendricks.png",
        sku: "DCW-0011",
        stripePriceId: "price_1SHYp2Krvd2Dq5RV2tqZN0d0",
        seoDescription: "Hand-poured candle in an upcycled Hendrick's Gin bottle.",
      },
      {
        slug: "grand-marnier-candle",
        name: "Grand Marnier Candle",
        price: 24.99,
        image: "/images/groundmarnier.png",
        sku: "DCW-0012",
        stripePriceId: "price_1SHYpMKrvd2Dq5RVgF9mIHev",
        seoDescription: "Hand-poured candle in an upcycled Grand Marnier bottle.",
      },
      {
        slug: "woodford-reserve-candle",
        name: "Woodford Reserve Candle",
        price: 29.99,
        image: "/images/woodford.png",
        sku: "DCW-0013",
        stripePriceId: "price_1SHYpXKrvd2Dq5RVh4qF83pQ",
        seoDescription: "Hand-poured candle in an upcycled Woodford Reserve bottle.",
        bestSeller: true,
      },
      {
        slug: "1800-tequila-candle",
        name: "1800 Tequila Candle",
        price: 24.99,
        image: "/images/placeholder.png",
        sku: "DCW-0014",
        stripePriceId: "price_1SHYpmKrvd2Dq5RVdRKMJMf2",
        seoDescription: "Hand-poured candle in an upcycled 1800 Tequila bottle.",
      },
      {
        slug: "bulleit-bourbon-candle",
        name: "Bulleit Bourbon Candle",
        price: 24.99,
        image: "/images/placeholder.png",
        sku: "DCW-0015",
        stripePriceId: "price_1SHYpzKrvd2Dq5RVFMkda0YX",
        seoDescription: "Hand-poured candle in an upcycled Bulleit Bourbon bottle.",
        bestSeller: true,
      },
  ];
  
  export function getProduct(slug: string) {
    return products.find((p) => p.slug === slug);
  }
  